x-server: &server
  image: ${DOCKER_REGISTRY-}server
  hostname: 'aerserver'
  build:
    context: .
    dockerfile: Server/Dockerfile
  environment: &server-environment
    ASPNETCORE_HTTP_PORTS: 8080
    DB_HOST: ${DB_HOST}
    DB_PORT: ${DB_PORT}
    DB_NAME: ${DB_NAME}
    DB_USER: ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
  ports:
    - 5000:8080
  networks:
    - wedding

services:

  server-dev:
    <<: *server
    profiles:
      - dev
    environment:
      <<: *server-environment
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db

  server-prod:
    <<: *server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aerserver.rule=Host(`amandineetromain.fr`)"
      - "traefik.http.routers.aerserver.entrypoints=websecure"
      - "traefik.http.routers.aerserver.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik"
    container_name: wedding-server
    profiles:
      - prod
    environment:
      <<: *server-environment
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - wedding
      - traefik

  db:
    profiles:
      - dev
    image: postgres:17
    hostname: 'aerdb'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    command: -p ${DB_PORT}
    expose:
      - '${DB_PORT}'
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - aer-pgdata:/var/lib/postgresql/data
    networks:
      - wedding

volumes:
  aer-pgdata:
    external: true

networks:
  wedding:
    external: true
  traefik:
    external: true