 @Server_HostAddress = http://localhost:5000/api
#@Server_HostAddress = http://amandineetromain.fr/api

GET {{Server_HostAddress}}/user/users
Accept: application/json

###

GET {{Server_HostAddress}}/user/pa.covet
Accept: application/json

###

POST {{Server_HostAddress}}/user
Content-Type: application/json

{
  "firstName": "PA",
  "lastName": "COVET",
  "userName": "pa.covet",
  "role": 1,
  "Invitation": "11111"
}

###

DELETE {{Server_HostAddress}}/user/3
Content-Type: application/json

###

GET {{Server_HostAddress}}/form/forms
Accept: application/json

###

POST {{Server_HostAddress}}/form
Content-Type: application/json

{
  "userId": "1",
  "confirmedDays": "01111",
  "mealChoice": 2,
  "foodAllergy": null,
  "musicRecommendation": "TSR Gros !"
}

###

GET {{Server_HostAddress}}/nawak
Accept: application/json

###

GET {{Server_HostAddress}}/user/search?query=cov
Accept: application/json
