#@Server_HostAddress = http://localhost:5000/api
@Server_HostAddress = http://amandineetromain.fr/api

GET {{Server_HostAddress}}/user/users
Accept: application/json

###

GET {{Server_HostAddress}}/user?userName=pa.covet
Accept: application/json

###

GET {{Server_HostAddress}}/user/1
Accept: application/json

###

POST {{Server_HostAddress}}/user
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "test",
  "userName": "test.test",
  "role": 1,
  "invitation": "11111"
}

###

DELETE {{Server_HostAddress}}/user/56
Content-Type: application/json

###

GET {{Server_HostAddress}}/form/forms
Accept: application/json

###

POST {{Server_HostAddress}}/form
Content-Type: application/json

{
  "userId": "1",
  "confirmedDays": "01111",
  "mealChoice": 2,
  "foodAllergy": null,
  "musicRecommendation": "TSR Gros !"
}

###

GET {{Server_HostAddress}}/nawak
Accept: application/json

###

GET {{Server_HostAddress}}/user/search?query=arn
Accept: application/json

###

POST {{Server_HostAddress}}/user
Content-Type: application/json

{
  "firstName": "Lundi",
  "lastName": "Jeudi",
  "userName": "lj.fake",
  "role": 0,
  "Invitation": "11110"
}

###

POST {{Server_HostAddress}}/user
Content-Type: application/json

{
  "firstName": "Mardi",
  "lastName": "Only",
  "userName": "ma.fake",
  "role": 0,
  "Invitation": "01000"
}

###

POST {{Server_HostAddress}}/user
Content-Type: application/json

{
  "firstName": "Mercredi",
  "lastName": "Only",
  "userName": "me.fake",
  "role": 0,
  "Invitation": "00100"
}

###

POST {{Server_HostAddress}}/user
Content-Type: application/json

{
  "firstName": "Mardi",
  "lastName": "Jeudi",
  "userName": "mj.fake",
  "role": 0,
  "Invitation": "01110"
}